//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarCodeSub.ezService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ezService.ITCI_Ser")]
    public interface ITCI_Ser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCI_Ser/GetBillInfo", ReplyAction="http://tempuri.org/ITCI_Ser/GetBillInfoResponse")]
        string GetBillInfo(string Username, string Password, string CustomerId, int BillType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCI_Ser/SendData", ReplyAction="http://tempuri.org/ITCI_Ser/SendDataResponse")]
        int SendData(string Username, string Password, string BillId, string PayId, string rrn, int Kind, System.DateTime PayDate, string BankId, string AdditionalData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITCI_Ser/GetBillDocument", ReplyAction="http://tempuri.org/ITCI_Ser/GetBillDocumentResponse")]
        System.IO.Stream GetBillDocument(string username, string password, string telno, bool online);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITCI_SerChannel : BarCodeSub.ezService.ITCI_Ser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TCI_SerClient : System.ServiceModel.ClientBase<BarCodeSub.ezService.ITCI_Ser>, BarCodeSub.ezService.ITCI_Ser {
        
        public TCI_SerClient() {
        }
        
        public TCI_SerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TCI_SerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TCI_SerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TCI_SerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetBillInfo(string Username, string Password, string CustomerId, int BillType) {
            return base.Channel.GetBillInfo(Username, Password, CustomerId, BillType);
        }
        
        public int SendData(string Username, string Password, string BillId, string PayId, string rrn, int Kind, System.DateTime PayDate, string BankId, string AdditionalData) {
            return base.Channel.SendData(Username, Password, BillId, PayId, rrn, Kind, PayDate, BankId, AdditionalData);
        }
        
        public System.IO.Stream GetBillDocument(string username, string password, string telno, bool online) {
            return base.Channel.GetBillDocument(username, password, telno, online);
        }
    }
}
